In [14]:

from google.colab import files
uploaded=files.upload()

Saving cricket_stats.csv to cricket_stats.csv

In [15]:
import pandas as pd
import numpy as np

df=pd.read_csv("cricket_stats.csv")
df

      player          team  matches    runs  average  strike_rate  centuries
0      Virat         India     50.0  2400.0     54.5         92.3        8.0
1      Rohit         India     48.0  2100.0     48.2         88.7        6.0
2      Babar      Pakistan     45.0  2050.0     51.3         84.5        7.0
3     Warner     Australia     42.0  1900.0     47.1         95.6        5.0
4       Root       England     44.0  1850.0     46.8         78.2        4.0
5       Kane   New Zealand     40.0  1700.0     44.5         73.4        3.0
6      Smith     Australia     41.0  1780.0     45.6         79.8        NaN
7     Rizwan      Pakistan     38.0  1500.0      NaN         86.2        2.0
8    Buttler       England     39.0     NaN     42.1        105.4        3.0
9      Rahul         India      NaN  1600.0     43.2         89.1        3.0
10    Bavuma  South Africa     30.0  1100.0     38.9         68.5        1.0
11  Mitchell   New Zealand     28.0     NaN     40.2         82.3        2.0

In [16]:
df.head()

   player       team  matches    runs  average  strike_rate  centuries
0   Virat      India     50.0  2400.0     54.5         92.3        8.0
1   Rohit      India     48.0  2100.0     48.2         88.7        6.0
2   Babar   Pakistan     45.0  2050.0     51.3         84.5        7.0
3  Warner  Australia     42.0  1900.0     47.1         95.6        5.0
4    Root    England     44.0  1850.0     46.8         78.2        4.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player       12 non-null     object
 1   team         12 non-null     object
 2   matches      11 non-null     float64
 3   runs         10 non-null     float64
 4   average      11 non-null     float64
 5   strike_rate  12 non-null     float64
 6   centuries    11 non-null     float64
dtypes: float64(5), object(2)
memory usage: 804.0+ bytes

In [19]:
df.describe()

         matches         runs    average  strike_rate  centuries
count  11.000000    10.000000  11.000000    12.000000  11.000000
mean   40.454545  1798.000000  45.672727    85.333333   4.000000
std     6.758160   358.292246   4.640709    10.000212   2.236068
min    28.000000  1100.000000  38.900000    68.500000   1.000000
25%    38.500000  1625.000000  42.650000    79.400000   2.500000
50%    41.000000  1815.000000  45.600000    85.350000   3.000000
75%    44.500000  2012.500000  47.650000    89.900000   5.500000
max    50.000000  2400.000000  54.500000   105.400000   8.000000

In [20]:
df.isnull().sum()

player         0
team           0
matches        1
runs           2
average        1
strike_rate    0
centuries      1
dtype: int64

In [23]:
df['average']=df['average'].fillna(df['average'].mean())
df['matches']=df['matches'].fillna(df['matches'].mean())
df['runs']=df['runs'].fillna(df['runs'].mean())
df['centuries']=df['centuries'].fillna(0)

# Q1 Who has the highest average?

In [24]:

top_avg_player=df.loc[df['average'].idxmax()]['player']
print(f"Best average: {top_avg_player}")

Best average: Virat

# Q2 Which team has the most total runs combined?

In [27]:
most_total_runs=df.groupby('team')['runs'].sum()
team_with_most_runs=most_total_runs.idxmax()
print(f"Team with most runs: {team_with_most_runs}")

Team with most runs: India

# Q3 Who has the best strike rate among players with more than 40 matches?

In [28]:
filteration=df[df['matches']>40]
best_strike_rate=filteration.loc[filteration['strike_rate'].idxmax(),'player']
print(f"Best strike rate (40+ matches): {best_strike_rate}")

Best strike rate (40+ matches): Warner

#Q4 What's the average number of centuries across all players?

In [30]:
avg_num_of_centuries=df['centuries'].mean()
print(f"Average number of centuries: {avg_num_of_centuries:.2f}")

Average number of centuries: 3.67

#Q5 Rank all players by runs, highest to lowest

In [38]:
ranking=df.sort_values(by='runs',ascending=False)
print(ranking[['player','runs']])

      player    runs
0      Virat  2400.0
1      Rohit  2100.0
2      Babar  2050.0
3     Warner  1900.0
4       Root  1850.0
8    Buttler  1798.0
11  Mitchell  1798.0
6      Smith  1780.0
5       Kane  1700.0
9      Rahul  1600.0
7     Rizwan  1500.0
10    Bavuma  1100.0

In [42]:
print("=== Cricket Stats Report ===")
print(f"Best average: {top_avg_player}") #Q1
print(f"Team with most runs: {team_with_most_runs}") #Q2
print(f"Best strike rate (40+ matches): {best_strike_rate}") #Q3
print(f"Average number of centuries: {avg_num_of_centuries:.2f}") #Q4
print(ranking[['player','runs']]) #Q5

=== Cricket Stats Report ===
Best average: Virat
Team with most runs: India
Best strike rate (40+ matches): Warner
Average number of centuries: 3.67
      player    runs
0      Virat  2400.0
1      Rohit  2100.0
2      Babar  2050.0
3     Warner  1900.0
4       Root  1850.0
8    Buttler  1798.0
11  Mitchell  1798.0
6      Smith  1780.0
5       Kane  1700.0
9      Rahul  1600.0
7     Rizwan  1500.0
10    Bavuma  1100.0